# Generated by Django 5.1.15 on 2026-07-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "blurb",
                    models.CharField(
                        help_text="Short line shown on cards.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Longer description for the listing and product page."
                    ),
                ),
                (
                    "lead",
                    models.CharField(
                        blank=True,
                        help_text="Optional subtitle under the title on the book page.",
                        max_length=300,
                    ),
                ),
                ("cover", models.ImageField(upload_to="books/covers/")),
                (
                    "price",
                    models.CharField(
                        help_text='Display price, e.g. "₹99".', max_length=40
                    ),
                ),
                (
                    "online_price",
                    models.CharField(
                        blank=True,
                        default="₹49",
                        help_text='Read-online price, e.g. "₹49". Leave blank to hide.',
                        max_length=40,
                    ),
                ),
                (
                    "read_time",
                    models.CharField(help_text='e.g. "2 hrs read".', max_length=60),
                ),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "First Edition, 2026" or "Coming soon".',
                        max_length=120,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Uncheck for Coming Soon books."
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=True, help_text="Show on the homepage carousel."
                    ),
                ),
                (
                    "has_reader",
                    models.BooleanField(
                        default=False,
                        help_text="Show the Read Online button (uses the shared reader page).",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text='e.g. "Chapter One".', max_length=80),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="studio.book",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
