# Generated by Django 5.1.15 on 2026-07-23 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0002_book_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="online_price_paise",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Read-online price in paise (₹49 = 4900). 0 to disable paid online.",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="price_paise",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Download price in paise for Razorpay (₹99 = 9900).",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("download", "Download"), ("online", "Read Online")],
                        default="download",
                        max_length=20,
                    ),
                ),
                ("amount_paise", models.PositiveIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=64, unique=True)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=64)),
                ("razorpay_signature", models.CharField(blank=True, max_length=255)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                ("buyer_contact", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="studio.book",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
