# Generated by Django 5.1.15 on 2026-07-23 10:44

import studio.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0003_book_online_price_paise_book_price_paise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf",
            field=models.FileField(
                blank=True,
                help_text="Private PDF delivered after download purchase (email + browser).",
                storage=studio.storage.PrivateMediaStorage(),
                upload_to="books/pdfs/",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="download_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
