# Generated by Django 5.1.15 on 2026-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0004_book_pdf_purchaseorder_download_token_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("razorpay_payment_id", ""), _negated=True),
                fields=("razorpay_payment_id",),
                name="unique_razorpay_payment_id_when_set",
            ),
        ),
    ]
