BOOKS = [
    {
        "slug": "questioning-the-marriage-system",
        "title": "Questioning the Marriage System",
        "blurb": "Rethinking tradition, equality & freedom.",
        "description": "A quiet, honest exploration of the traditions, roles, and expectations many of us inherit without ever choosing.",
        "cover": "images/book-cover.jpg",
        "price": "₹99",
        "read_time": "2 hrs read",
        "edition": "First Edition, 2026",
        "sheet_key": "download",
        "detail_url_name": "book",
        "available": True,
    },
    {
        "slug": "letters-to-my-younger-self",
        "title": "Letters to My Younger Self",
        "blurb": "A gentle guide to healing & growing.",
        "description": "Letters written for the younger self — soft guidance for anyone learning to grow without abandoning who they were.",
        "cover": "images/book-cover-02.jpg",
        "price": "₹149",
        "read_time": "3 hrs read",
        "edition": "Coming soon",
        "sheet_key": "download2",
        "detail_url_name": None,
        "available": False,
    },
]
